version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "sqlite"
    volumes:
      - ./database:/app/database
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - app